# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  cryptothunebot:
    image: cryptothunebot
    build:
      context: .
      dockerfile: CryptoThune.Bot/Dockerfile
    ports:
      - 80
